name: Lunes Auto Login (Python)

on:
  schedule:
    - cron: "0 1 */14 * *"
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run login script
        run: python login.py
        env:
          LUNES_USERNAME: ${{ secrets.LUNES_USERNAME }}
          LUNES_PASSWORD: ${{ secrets.LUNES_PASSWORD }}
          SERVER_ID: ${{ secrets.SERVER_ID }}
          SERVER_UUID: ${{ secrets.SERVER_UUID }}
          NODE_HOST: ${{ secrets.NODE_HOST }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
